[[dependencies]]
name = "clamor_sound_manager"
url = "https://github.com/SirLich/godot-clamor"
version = "main"
version_lock = "0d1d8e16102b047619ad698da3123248dfc10c52"
destination = "addons/sound_manager"
source = "addons/sound_manager"

[[dependencies]]
name = "clamor"
url = "https://github.com/SirLich/godot-clamor"
version = "main"
version_lock = "0d1d8e16102b047619ad698da3123248dfc10c52"
destination = "addons/clamor"
source = "addons/clamor"

[[dependencies]]
name = "editor-tweaks"
url = "https://github.com/SirLich/godot-editor-tweaks"
version = "refs/heads/main"
version_lock = "1cb86de593973f5dc5ffe3a910bac301c4ee9098"
destination = "addons/editor_tweaks"
source = "addons/editor_tweaks"

[[dependencies]]
name = "stylebox-fancy"
url = "https://github.com/SirLich/StyleBoxFancy.git"
version = "main"
version_lock = "8d0a6a75713f3d4a58a9af096b96e09d3b839b95"
destination = "addons/StyleBoxFancy"
source = "addons/StyleBoxFancy"
